# Generated by Django 5.0 on 2023-12-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
