# Generated by Django 5.0 on 2023-12-16 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_remove_pokemon_number_remove_pokemon_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='pokedex.team'),
        ),
    ]
