# Generated by Django 5.0 on 2024-01-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_fight_last_message_fight_team1_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='last_message',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fight',
            name='team1_pokemon_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fight',
            name='team2_pokemon_number',
            field=models.IntegerField(default=1),
        ),
    ]
