# Generated by Django 5.0 on 2024-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0010_fight_team2_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='team1_action',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fight',
            name='team2_action',
            field=models.IntegerField(default=0),
        ),
    ]
