# Generated by Django 5.0 on 2024-01-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0011_alter_fight_team1_action_alter_fight_team2_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='turn',
        ),
    ]
