# Generated by Django 5.0 on 2024-01-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0012_remove_fight_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
